blogProject/blogProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls')),
]

blogProject/comments/urls.py
#!/usr/bin/python3
"""blogProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from comments import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<article_id>[0-9]+)/$', views.article_comment, name='article_comment'),
]

blogProject/home/urls.py
#!/usr/bin/python3
"""blogProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from home import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index),

    url(r'^about/$', views.about),

    url(r'^full_(\d+)/$', views.full),

    url(r'^contact/$', views.contact),

    url(r'^details_(\d+)/$', views.details, name='details'),


]

blogProject/home/models.py
#!/usr/bin/python3
# -*-coding:utf8-*-
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django_markdown.models import MarkdownField
from tinymce.models import HTMLField


class Category(models.Model):
    """
    分类名
    """
    name = models.CharField(max_length=100, verbose_name='分类')

    def __str__(self):
        # 返回类名
        return self.name

    class Meta:
        # 元类
        db_table = "Category"
        verbose_name = "分类"
        verbose_name_plural = "分类s"


class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(max_length=100, verbose_name='标签')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Tag"
        verbose_name = "标签"
        verbose_name_plural = "标签s"


class Article(models.Model):
    """
    文章
    """
    title = models.CharField(max_length=100, verbose_name='标题')
    # 文章简介   blank=True 表示可以不写 没有的话　　此字段必须要有值
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='简介')

    content = models.TextField(verbose_name='内容')
    # 富文本
    # content = HTMLField(verbose_name='内容')
    # content = MarkdownField()

    create_time = models.DateTimeField(verbose_name='建立时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')  # 修改时间
    # 分类外键
    category = models.ForeignKey(Category, verbose_name='分类')
    # 多对多　文章和标签
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')

    # 作者 一对多关系一篇文章只有一个作者
    # author = models.ForeignKey(User)

    on_click = models.IntegerField(default=0, verbose_name='点击量')

    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('home:details', kwargs={'pk': self.pk})

    # 元类
    class Meta:
        db_table = "Article"
        verbose_name = "文章"
        verbose_name_plural = "文章s"

blogProject/home/views.py
#!/usr/bin/python3
import markdown
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from comments.forms import CommentForm
from comments.models import Comment
from home.models import Article


def index(request):
    # return HttpResponse('hello world')

    # 通过id倒叙查询文章
    article_list = Article.objects.filter().order_by('-id')[:3]  # .order_by('-id')

    for item in article_list:
        item.content = markdown.markdown(item.content,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                             'markdown.extensions.toc',
                                         ])

    context = {'title': '首页', 'article_list': article_list, 'show_right': True}
    return render(request, 'home/index.html', context)


def about(request):
    context = {'title': '关于'}
    return render(request, 'home/about.html', context)


def full(request, current_page):
    """

    :param request:
    :param current_page: 当前页
    :return:
    """
    article_list = Article.objects.filter().order_by('-id')
    # 分页对象　
    paginator = Paginator(article_list, 4)
    # 表示当前是第几页
    page = paginator.page(current_page)

    for item in page:
        item.content = markdown.markdown(item.content,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                             'markdown.extensions.toc',
                                         ])

    context = {'title': '博客', 'page': page}
    return render(request, 'home/full-width.html', context)


def contact(request):
    """联系方式"""
    context = {'title': '联系'}
    return render(request, 'home/contact.html', context)


def details(request, article_id):
    """文章详细列表"""
    article = get_object_or_404(Article, pk=article_id)
    # 点击量加１
    article.on_click += 1
    article.save()

    article.content = markdown.markdown(article.content,
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',
                                        ])
    comment_num = Comment.objects.filter(article=article_id).count()
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = article.comment_set.all()

    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {'title': '文章详情',
               'article': article,
               'form': form,
               'comment_list': comment_list,
               'comment_num': comment_num,
               'show_right': True,
               }
    return render(request, 'home/details.html', context)
    # else:
    #     return HttpResponse('没有此文章，操作有误!自己返回!就是这么傲娇 :) ')

blogProject/templates/home/about.html
{% extends 'base.html' %}


{% block content %}
	<body id="page">


		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="/static/img/me.jpg" alt="Developer Image">
								</figure>
								<p>　　<i>一个coder:</i> wg 是我的名字首尾字母的缩写，有人问我为什么不是名字首字母缩写ws了，以前玩游戏的时候，比如有个人实力很厉害，总有人就会说他开wg了(由于外挂俩字被和谐了),所以我选wg作为我的昵称.</p>
								<p>...........</p>
								<div class="height-40px"></div>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
        {% endblock %}
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->

		<script src="/static/js/script.js"></script>
		
	</body>

blogProject/templates/home/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blogProject/templates/home/details-bat.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}


{% block content %}


    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">


                        <article class="post post-1">
                            <header class="entry-header">
                                <h1 class="entry-title">
                                    <a href="#">{{ article.title }}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="post-category"><a href="#">{{ article.category }}</a></span>
                                    <span class="post-date"><a href="#">
                                        <time class="entry-date" datetime="2012-11-09T23:15:57+00:00">
                                            {{ article.create_time }}</time></a></span>
                                    <span class="post-author"><a href="#">@wgPython</a></span>
                                    <span class="comments-link"><a href="#">4 评论</a></span>
                                    <span class="views-count"><a href="#">588 阅读</a></span>
                                </div>
                            </header>
                            <div class="entry-content clearfix">
                                <p>{{ article.content | safe }}</p>
                            </div>
                        </article>

                </main>
                <aside class="col-md-4">
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最新文章</h3>
                        <ul>
                            <li>
                                <a href="#">Django 博客开发入门教程：前言</a>
                            </li>
                            <li>
                                <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                            </li>
                            <li>
                                <a href="#">部署 Django 博客</a>
                            </li>
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3>
                        <ul>
                            <li>
                                <a href="#">2017 年 5 月</a>
                            </li>
                            <li>
                                <a href="#">2017 年 4 月</a>
                            </li>
                            <li>
                                <a href="#">2017 年 3 月</a>
                            </li>
                        </ul>
                    </div>

                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3>
                        <ul>
                            <li>
                                <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                            </li>
                            <li>
                                <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                            </li>
                            <li>
                                <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                            </li>
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3>
                        <ul>
                            <li>
                                <a href="#">Django</a>
                            </li>
                            <li>
                                <a href="#">Python</a>
                            </li>
                            <li>
                                <a href="#">Java</a>
                            </li>
                            <li>
                                <a href="#">笔记</a>
                            </li>
                            <li>
                                <a href="#">文档</a>
                            </li>
                            <li>
                                <a href="#">AngularJS</a>
                            </li>
                            <li>
                                <a href="#">CSS</a>
                            </li>
                            <li>
                                <a href="#">JavaScript</a>
                            </li>
                            <li>
                                <a href="#">Snippet</a>
                            </li>
                            <li>
                                <a href="#">jQuery</a>
                            </li>
                        </ul>
                    </div>
                    <div class="rss">
                        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
{% endblock %}

blogProject/templates/home/details.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block content %}

    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="#">{{ article.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ article.category }}</a></span>
                <span class="post-date"><a href="#">
                                        <time class="entry-date" datetime="2012-11-09T23:15:57+00:00">
                                            {{ article.create_time }}</time></a></span>
                <span class="post-author"><a href="#">@wgPython</a></span>
                <span class="comments-link"><a href="#">{{ comment_num }}评论</a></span>
                <span class="views-count"><a href="#">{{ article.on_click }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ article.content | safe }}</p>
        </div>
    </article>
{% endblock %}
{% block comment %}
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:article_comment' article.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
{#                <div class="col-md-4">#}
{#                    <label for="{{ form.url.id_for_label }}">URL：</label>#}
{#                    {{ form.url }}#}
{#                    {{ form.url.errors }}#}
{#                </div>#}
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_num }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

blogProject/templates/home/full-width.html
{% extends 'base.html' %}
<!-- meta -->

{% block head %}
    <link rel="stylesheet" href="/static/css/jquery.pagination.css"/>
    <script src="/static/js/jquery.pagination.min.js"></script>
{% endblock %}

{% block content %}
    <body>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">

                    {% block article %}
                        {% for article in page %}
                            <article class="post post-{{ forloop.counter }}">
                                <header class="entry-header">
                                    <h1 class="entry-title">
                                        <a href="#">{{ article.title }}</a>
                                    </h1>
                                    <div class="entry-meta">
                                        <span class="post-category"><a href="#">{{ article.category }}</a></span>
                                        <span class="post-date"><a href="#"><time class="entry-date"
                                                                                  datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
                                        <span class="post-author"><a href="#">@wgPython</a></span>
                                        <span class="comments-link"><a href="#">4 评论</a></span>
                                        <span class="views-count"><a href="#">{{ article.on_click }} 阅读</a></span>
                                    </div>
                                </header>
                                <div class="entry-content clearfix">
                                    <p>{{ article.content | truncatewords:"10" | safe }}</p>
                                    <div class="read-more cl-effect-14">
                                        <a href="/details_{{ article.id }}" class="more-link">继续阅读 <span
                                                class="meta-nav">→</span></a>
                                    </div>
                                </div>
                            </article>
                        {% empty %}
                            <div class="no-post">暂时还没有发布的文章！</div>
                        {% endfor %}
                    {% endblock %}


                    <div class="box" style="margin-right: auto">
                        <div id="pagination" class="page"></div>
                    </div>
                    <script>
                        $("#pagination").pagination({
                            currentPage: {{ page.number }},// 当前页数
                            totalPage: {{ page.paginator.num_pages}},// 总页数
                            isShow: false,// 是否显示首尾页
                            count: 5,// 显示个数
                            homePageText: "首页",// 首页文本
                            endPageText: "尾页",// 尾页文本
                            prevPageText: "上一页",// 上一页文本
                            nextPageText: "下一页",// 下一页文本
                            callback: function (current) {
                                // 回调,current(当前页数)
                                {#                        alert(current);#}
                                {# $("#current").text(current)　//当前页 #}
                                {#                        location.href = '/product_list_{{ current_type.id }}_' + current + '/?order_by={{ order_by }}'#}
                                {#                        location.href = '/full_{{ current }}'#}
                                location.href = '/full_' + current
                            }
                        });
                    </script>

                </main>
            </div>
        </div>
    </div>
{% endblock %}

blogProject/templates/home/index.html
{% extends 'base.html' %}



{% block head %}

{% endblock %}


{% block content %}



                    {% for article in article_list %}
                        <article class="post post-{{ forloop.counter }}">
                            <header class="entry-header">
                                <h1 class="entry-title">
                                    <a href="#">{{ article.title }}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="post-category"><a href="#">{{ article.category }}</a></span>
                                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                              datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
                                    <span class="post-author"><a href="#">@wgPython</a></span>
                                    <span class="comments-link"><a href="#">4 评论</a></span>
                                    <span class="views-count"><a href="#">{{ article.on_click }} 阅读</a></span>
                                </div>
                            </header>
                            <div class="entry-content clearfix">
                                <p>{{ article.content | truncatewords:"10"| safe }}</p>
                                <div class="read-more cl-effect-14">
                                    <a href="/details_{{ article.id }}" class="more-link">继续阅读 <span
                                            class="meta-nav">→</span></a>
                                </div>
                            </div>
                        </article>
                    {% empty %}
                        <div class="no-post">暂时还没有发布的文章！</div>
                    {% endfor %}

                    <!-- 简单分页效果
                    -->

    {% endblock %}

{#                <aside class="col-md-4">#}
{#                    <div class="widget widget-recent-posts">#}
{#                        <h3 class="widget-title">最新文章</h3>#}
{##}
{#                        <ul>#}
{##}
{#                            <li>#}
{#                                <a href="#">111111</a>#}
{#                            </li>#}
{##}
{#                        </ul>#}
{#                    </div>#}
{#                    <div class="widget widget-archives">#}
{#                        <h3 class="widget-title">归档</h3>#}
{#                        <ul>#}
{#                            <li>#}
{#                                <a href="#">2017 年 5 月</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">2017 年 4 月</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">2017 年 3 月</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{##}
{#                    <div class="widget widget-category">#}
{#                        <h3 class="widget-title">分类</h3>#}
{#                        <ul>#}
{#                            <li>#}
{#                                <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">Python 教程 <span class="post-count">(11)</span></a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{##}
{#                    <div class="widget widget-tag-cloud">#}
{#                        <h3 class="widget-title">标签云</h3>#}
{#                        <ul>#}
{#                            <li>#}
{#                                <a href="#">Django</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">Python</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">Java</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">笔记</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">文档</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">AngularJS</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">CSS</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">JavaScript</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">Snippet</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">jQuery</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                    <div class="rss">#}
{#                        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#                    </div>#}
{#                </aside>#}